# Generated by Django 4.0.4 on 2022-05-18 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ttcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_sale',
            name='be_left',
            field=models.ManyToManyField(blank=True, related_name='be_left', to='ttcapp.be_left'),
        ),
        migrations.AlterField(
            model_name='store_sale',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='store_sale',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
